# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build APK

on:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.2'
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - run: pwd && echo $KEY_JKS
    - run: echo $KEY_JKS > android/key.jks
    - run: cat android/key.jks
    - run: flutter pub get
    - run: flutter build apk --release --build-name ${{ steps.get_version.outputs.VERSION }}
    - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/whatnext-${{ steps.get_version.outputs.VERSION }}.apk
    - uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/whatnext-${{ steps.get_version.outputs.VERSION }}.apk
